### ISSUE TITLE
Provide a minimum example

### ISSUE THREAD

**Issue by Ailrun** [Pix4D/three-potree-loader#4]
I tried following code, but it didn't work.

```javascript
const renderer = new THREE.WebGLRenderer();
renderer.setSize(0, 0);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(45, NaN, 0.1, 1000);

const potree = new Potree();

const el = document.getElementById('target');
const { width, height } = el.getBoundingClientRect();
camera.aspect = width / height;
camera.updateProjectionMatrix();
renderer.setSize(width, height);
el.appendChild(renderer.domElement);

potree.loadPointCloud('', (url) => `http://localhost:4000/${url}`)
  .then((pco) => {
    scene.add(pco);
    scene.updateMatrix();
  })
  .catch((err) => {
    console.log(err);
  });

Observable.interval(0, Scheduler.animationFrame)
  .map(() => {
    renderer.render(scene, camera);
  })
  .subscribe();
```

(My server (on localhost:4000) works fine and client get r.hrc and r.bin successfully, so it's probably client-side problem...)

Could you please provide a minimum example? Or could you give me hints to fix my invalid code?

**Comment by Ailrun** [comment]
Now I know How can display it (after long time of inspecting repo codes... :( ).

```js
const renderer = new THREE.WebGLRenderer();
renderer.setSize(0, 0);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(45, NaN, 0.1, 1000);

const potree = new Potree();

const el = document.getElementById('target');
const { width, height } = el.getBoundingClientRect();
camera.aspect = width / height;
camera.updateProjectionMatrix();
renderer.setSize(width, height);
el.appendChild(renderer.domElement);

potree.loadPointCloud('', (url) => `http://localhost:4000/${url}`)
  .then((pco) => {
    pco.material = new Potree.PointCloudMaterial({
      // Some options... (I use `size`s)
    });
    pco.toTreeNode(pco.root);
    scene.add(pco);
    scene.updateMatrix();
  })
  .catch((err) => {
    console.log(err);
  });

Observable.interval(0, Scheduler.animationFrame)
  .map(() => {
    renderer.render(scene, camera);
  })
  .subscribe();
```

I still don't know this is best way to do this. It looks like there may exist a simpler way to do
```js
    pco.material = new Potree.PointCloudMaterial({
      // Some options... (I use `size`s)
    });
    pco.toTreeNode(pco.root);
    scene.add(pco);
```
since it updates `pco.root` by passing `pco.root`.

and I still don't know how can load things hierarchically in valid way...

**Comment by Ailrun** [comment]
https://github.com/Ailrun/three-potree-loader-example

**Comment by hccampos** [comment]
Hi @Ailrun, I am glad you found a way to make some of it work and really appreciate you trying to come up with an example.

What seems to be missing in your code is calling `potree.updatePointClouds([pco], camera, renderer)` every frame, or at least whenever your camera moves/changes. This is the method which keeps the octree and update-to-date by updating node visibilities and loading/unloading necessary nodes.

That being said, there should probably be some refactoring to support calling `update` directly on a single `PointCloudOctree`. The original Potree doesn't do it because it keeps track of the maximum number of points and keeps a global LRU queue to check which nodes need to be unloaded.

**Comment by Ailrun** [comment]
@hccampos Thank you for your kind and detail answer! I really appriciate it.
I will try it and if it works greatly I will update example too!

Also, can I send a PR for including example to readme?

**Comment by hccampos** [comment]
@Ailrun No problem, am I really happy to help. And a PR for the example would be super great. Could you try to remove the rxjs dependency and instead just use `requestAnimationFrame`? We are also using rxjs at Pix4D but I felt like it was nicer to keep the potree loader as abstract as possible.

**Comment by Ailrun** [comment]
Of course! It's just added for simplicity for my try-and-error experiments. When I update it I also remove the dependency.

**Comment by hccampos** [comment]
@Ailrun Cool! In the meantime I updated some stuff in your example and made it work on CodeSandbox. It also has some comments.

[![Edit Three Potree Loader Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yw2p3446j9?autoresize=1&view=preview)

**Comment by Ailrun** [comment]
@hccampos Can I make one more question? How can I load other binaries (`r[numbers].bin`s)? Should I use `pcoGeometry.root.traverse`?

**Comment by Ailrun** [comment]
Can I use something like 
https://github.com/potree/potree/blob/916e388069adc962d40fbf30209c0be704878675/src/scenegraph/Camera.js#L177
this one?

**Comment by hccampos** [comment]
Yes, you can use something like that, but it is more of a generic ThreeJS thing. I have seen some examples on StackOverflow and/or on the ThreeJS forum.

https://discourse.threejs.org/t/camera-zoom-to-fit-object/936/2

**Comment by Ailrun** [comment]
@hccampos Actually I made that question since potree makes its frustom somewhat different way from normal three.js way.

Usually in three.js, frustom is camera.projectionMatrix times camera.matrixWordlInverse, where in potree, we mutliply pco.matrix, so I though it's not general question about three.js.

**Comment by Ailrun** [comment]
To make it equal (A * B * C = A * B, so if A * B is inversible, C should be the identity matrix), I should make `pco.matrixWorld` equal to identity matrix, i.e. set `pco.position` to (0, 0, 0).
So, finally I make an working example...
