### ISSUE TITLE
Clarify clearing of clouds from scene

### ISSUE THREAD

**Issue by eljenso** [Pix4D/three-potree-loader#5]
I'm writing an application which allows changing of the contents of the scene, including point clouds.
This is the function which adds point clouds to the scene:
```ts
private async _addPotreeCloud(
  potree: Element_element_PotreeCloud,
): Promise<any> {
  const pco = await new PointCloud(
    potree.filename,
    potree.baseurl,
    new Vector3(
      potree.pose.scale.x,
      potree.pose.scale.y,
      potree.pose.scale.z,
    ),
  ).getpco();

  pco.position.set(
    potree.pose.position.x,
    potree.pose.position.y,
    potree.pose.position.z,
  );
  pco.userData = { id: potree.id, parentId: potree.parent.id };
  this.scene.add(pco);
}
```

When changing contents, following code is executed (initially executed with the scene) before adding anything, in order to remove everything from scene:
```ts
private _clearScene(object): void {
  while (object.children.length > 0) {
    this._clearScene(object.children[0]);
    object.remove(object.children[0]);
  }
  if (object.geometry) {
    object.geometry.dispose();
  }
  if (object.material) {
    object.material.dispose();
  }
  if (object.texture) {
    object.texture.dispose();
  }
}
```

But when making multiple changes of content, I saw in Chrome that the number of threads is rising.
See this screencast:
https://gfycat.com/SilentRecentClownanemonefish

Am I doing something wrong in `_clearScene`? Or are the web workers not properly stopped?

**Comment by hccampos** [comment]
Hi! Thank you for reporting this. It definitely looks like a bug. I will see if I can fix it tomorrow morning.

**Comment by hccampos** [comment]
I added an example to the repo which lets you load and unload a point cloud. There is now a `dispose()` method which triggers the full disposal of a point cloud.

I'll soon make a new version available on NPM.

**Comment by eljenso** [comment]
Works, thanks!
